language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm run test
  - scripts/upload-stack.js -b antklim-cf-templates/simple-api -v $TRAVIS_BUILD_NUMBER
  - travis_wait scripts/deploy-stack.js -r ap-southeast-2 -n simple-api -e dev -b antklim-cf-templates/simple-api -v $TRAVIS_BUILD_NUMBER
