language: node_js
node_js:
  - "8"
before_install:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
script:
  - npm run test
after_script:
  - scripts/upload-stack.js -b antklim-cf-templates/simple-api -v $TRAVIS_BUILD_NUMBER
  - scripts/deploy-stack.js -r ap-southeast-2 -n simple-api -e dev -b antklim-cf-templates/simple-api -v $TRAVIS_BUILD_NUMBER
