language: node_js
node_js:
  - "8"
before_install:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
script:
  - npm run test
after_script:
  - scripts/deploy-stack.sh
